INSERT INTO spacecrafts (name, franchise, crew_capacity, speed, spacecraft_type, is_armed) VALUES
('USS Enterprise', 'Star Trek', 430, 9.6, 'Exploration', true),
('Millennium Falcon', 'Star Wars', 6, 1050, 'Freighter', true),
('X-Wing', 'Star Wars', 1, 1050, 'Starfighter', true),
('Y-Wing', 'Star Wars', 2, 950, 'Starfighter', true),
('Galactica', 'Battlestar Galactica', 2500, 8.0, 'Battlestar', true),
('Serenity', 'Firefly', 5, 1.5, 'Transport', false),
('Nebuchadnezzar', 'The Matrix', 7, 2.0, 'Hovercraft', false),
('Rocinante', 'The Expanse', 50, 20.0, 'Gunship', true),
('Eagle 5', 'Spaceballs', 2, 0.5, 'Space RV', false),
('Heart of Gold', 'Hitchhikers Guide', 3, 42.0, 'Research', false),
('Discovery One', '2001: A Space Odyssey', 6, 1.0, 'Exploration', false),
('Event Horizon', 'Event Horizon', 20, 50.0, 'Research', true),
('Slave I', 'Star Wars', 1, 1000, 'Fighter', true),
('Red Dwarf', 'Red Dwarf', 169, 1.0, 'Mining Ship', false),
('Normandy SR-2', 'Mass Effect', 60, 15.0, 'Stealth', true),
('Elysium', 'Elysium', 100, 12.0, 'Space Habitat', false),
('Vipers', 'Battlestar Galactica', 1, 15.0, 'Fighter', true),
('Sulaco', 'Aliens', 85, 8.0, 'Warship', true),
('Planet Express Ship', 'Futurama', 4, 25.0, 'Delivery', true),
('Swordfish II', 'Cowboy Bebop', 1, 13.0, 'Fighter', true);
